### PR TITLE
cPLSA algorithm for Intent-Aware Diversification

### PR DESCRIPTION
**Pull request by jacekwasilewski**
Hi @saulvargas 

This is not ready-to-merge code (needs JavaDocs etc.) but I wanted to share that before I start writing those.

Basically this PR is the code for the work I presented at RecSys this year.
To summarise:
- I slightly modified the interface of `PLSAFactorizer` - moved normalisation of vectors into methods; to use PLSA as a source probabilities for IA models we need different normalisation (like the one in PR#4) and this is done in `NormalizedPLSAFactorizer`
- I put all the cPLSA code (factorizer and IA models) in a separate module, I did not want to split those into diversity and mf and then add dependency on mf in diversity, this seems more consistent to me but I am open
- `CPLSAFactorizer` with `ExplicitFactorization` can be used to produce recommendations like PLSA, just with fixed and known factors
- `IAFactorizationModelFactory`, `PLSAIAFactorizationModelFactory` and `CPLSAIAFactorizationModelFactory` classes contain aspect and intent models - I decided to put them in one class each as these are created together and that is why there is this kind of "factory"
- examples for recommender and xQuAD re-ranking using cPLSA model

Performance-wise - I did not notice any huge issues.
Performance of cPLSA seems to be similar to PLSA on the same number of factors.

Possible drawbacks:
- current implementation of PLSA uses tables/vectors and it assumes these are dense, cPLSA makes these sparser; I had an implementation using sparse structures but the performance was lower, so if you use reasonable number of features (not like 10k..) I do not see huge benefit right now in sparse implementation; other thing is - if you have huge number of features probably you should not use cPLSA
- cPLSA aspect and intent models need to access internal matrices, and convert from U,I,F to uidx, iidx and fidx to get probabilities; but I am not sure if that could be done much better right now

Let me know what you think and if you are happy. If yes, I will prepare the final PR.

Jacek.

### CODE REVIEW

**Comment by saulvargas** [comment]
Great!

You know, as soon as I have some free time I take a look at it and let you know.

I read your paper a week ago and I really liked it!

Saúl

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

I took a look at your PR. It looks great! I have made some minor changes (check them at the jacekwasilewski-cplsa branch), and I would ask you to consider the following changes:
- Unless you envision other uses for the ExplicitFactorization class, I would suggest you to make internal to CPLSAFactorizer.
- Could you actually move the code in RankSys-cplsa to already existing modules? One effort I am doing for the next version (0.5) is to minimise the number of modules, as they are right now just too many.

Thanks again! Don't forget to add your paper to the list of references once the PR is accepted. If you wish, I can also tweet about it using the @ranksys account.

Saúl

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

Great, thanks a lot for your feedback! I will merge your changes when I get back to Dublin.
Right now I do not see other use for the ExplicitFactorization so making it internal is totally fine.

When it comes to the modules - should the CPLSAFactorizer go to the RankSys-mf module and aspect models to RankSys-diversity? Then the RankSys-diversity would depend on the RankSys-mf. That is what I had at the beginning but I was not sure if you would like it.

I will make these changes, add some comments and send the PR back probably around the next week.

Jacek.

**Comment by saulvargas** [comment]
Yes, moving code to RankSys-mf and RankSys-diversity makes sense to me.

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

I moved the code as discussed and commented the public parts of the code. Let me know if you notice anything that I missed or you would like me to add something.

Jacek.

**Comment by saulvargas** [comment]
Great work!

Could you please add you RecSys'16 paper to the list of references in the wiki and tweet about it so that I can retweet from the RankSys account?

**Comment by jacekwasilewski** [comment]
Done!

**Pull request merged**
