### PR TITLE
RankALS recommender

### PR DESCRIPTION
**Pull request by jacekwasilewski**
Implementation of: Takács, G., & Tikk, D. (2012). Alternating Least Squares for Personalized Ranking

### CODE REVIEW

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

I've been testing RankALS with my usual small testing setup: a 80-20% split with MovieLens 1M and the CF algorithms that are available in RankSys. These are the results:

| Method | P@20 |
| --- | --: |
| random | 0.0055 |
| pop | 0.1217 |
| ib-knn | 0.1929 |
| ub-knn | 0.2074 |
| plsa | 0.2112 |
| pzt | 0.2264 |
| hkv | 0.2264 |
| rankals_50_false | 0.2010 |
| rankals_50_true | 0.1474 |

All three PZT, HKV and RankALS have been trained with k = 50 and 20 iterations. RankALS takes about 60 seconds per iteration. That'a a lot when compared with HKV (5 seconds) and PZT (1 second).

Given this partial evidence (not better that other MF approaches and signifficantly slower), I am not very convinced that it makes an overall positive contribution to RankSys.

Could you please provide evidence that it is worth adding this algorithm to RankSys (e.g. any other dataset in which RankALS outperforms HKV)? Do you think it is possible to speed it up?

Cheers
Saúl

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

I am really surprised that it is that slow on your machine - I do not remember the numbers for it was not 12 times slower than the HKV when I was testing - I assume you do not calculate the error after each iteration, that takes   | Transaction | \* | Items operations |.

I will run some experiments again and will get back with some results. I do not remember right now if that outperforms HKV on Precision - here we have ranking-based objective, not prediction-based. The implementation right now follows equations from the paper, I will take a look it is possible to speed up some bits. Will get back to you.

Jacek.

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

I have run some small experiments on ML-1M and Yahoo! Music from KDD Cup 2011 Track2. However I used implicit version of them, so we only have 0s and 1s if the rating is 5 or above some threshold.
Generally RankALS does not outperform other MF algorithms in terms of the Precision, it does however in terms of ErrorRate (each user has set of items that are in the test set and random that are not in the test set, if we get their scores and rank, we measure how many items fail to be in the top items). ErrorRate was used in that KDD Cup as well.

RankALS is not commonly used, as well as ErrorRate and it uses non-standard way of evaluation.
So if you feel that it might not be useful to have it, because it is not a common case, no worries, I will keep it under my repo as an add-on. Please close the PR then.

When it comes to the performance, without calculating the error, HKV took 1.85s on average and RankALS 3.7s for one iteration.

Thanks,
Jacek.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski,

How is this ErrorRate metric different from 1 - recall?

I am conducting a more careful analysis of RankALS. I am restricted to ML1M as the only computer that I can use at the moment is my laptop. Worth-mentioning differences with respect to your evaluation setup are:
- For training, I do not discriminate between rating scores, everything is treated as useful implicit feedback.
- For evaluation, only ratings of 4 or more are relevant. The set of candidates to be ranked are all the ratings is every item the user did not have in training.
  However, I would be very surprised that they explain the differences we are observing.

The MF models for the three current implementations in RankSys (HKV, PZT and pLSA) and RankALS have been considered. I have tested different numbers of latent factors K = 5, 10, 20, 50, 100 which typically suffice for ML1M. HKV, PZT and RankALS are trained with 20 iterations each, pLSA required 100 iterations.

In terms of total execution time, these are the results:

| K | 5 | 10 | 20 | 50 | 100 |
| --- | --: | --: | --: | --: | --: |
| pLSA | 15.52 | 18.50 | 25.72 | 46.02 | 84.65 |
| PZT | 2.15 | 4.26 | 9.04 | 23.79 | 56.85 |
| HKV | 2.42 | 22.23 | 84.10 | 543.86 | 452.88 |
| RankALS(false) | 11.33 | 41.81 | 155.92 | 798.92 | 3,075.27 |
| RankALS(true) | 11.77 | 41.26 | 139.27 | 839.89 | 3,167.12 |

RankALS seems quite slow. I do not know how to explain the discrepancy between our results.

In terms of precision@20 (ratings in test >= 4 are considered relevant):

| K | 5 | 10 | 20 | 50 | 100 |
| --- | --: | --: | --: | --: | --: |
| pLSA | 0.16 | 0.18 | 0.20 | 0.21 | 0.21 |
| PZT | 0.17 | 0.21 | 0.22 | 0.23 | 0.20 |
| HKV | 0.17 | 0.21 | 0.23 | 0.23 | 0.20 |
| RankALS(false) | 0.17 | 0.19 | 0.20 | 0.20 | 0.19 |
| RankALS(true) | 0.13 | 0.15 | 0.16 | 0.15 | 0.12 |

And recall@20:

| K | 5 | 10 | 20 | 50 | 100 |
| --- | --: | --: | --: | --: | --: |
| pLSA | 0.20 | 0.22 | 0.25 | 0.29 | 0.29 |
| PZT | 0.20 | 0.26 | 0.29 | 0.31 | 0.28 |
| HKV | 0.21 | 0.26 | 0.30 | 0.31 | 0.27 |
| RankALS(false) | 0.20 | 0.24 | 0.26 | 0.26 | 0.25 |
| RankALS(true) | 0.16 | 0.19 | 0.21 | 0.20 | 0.16 |

For small values of K, RankALS(false) is better than pLSA. In the rest of cases, the current implementations in RankSys are better. The PZT still surprises me, it is only slightly worse than HKV but it is incredibly fast!

Given this results, I am inclined not to accept for the moment the PR. I am specially worried about the slowness that I am observing in RankALS. Otherwise, even when it does not seem to outperform the others, I would consider it a great contribution.

Best,
Saúl

**Pull request closed without merging**
