### PR TITLE
Recall metric

### PR DESCRIPTION
**Pull request by jacekwasilewski**
Recall metric added - maybe you would like to merge it to the main project.

### CODE REVIEW

**Comment by saulvargas** [comment]
Thanks @jacekwasilewski!

Before adding this metric to the framework, I need a question to be answered: what's the use case or situation that the recall metric models in a Recommender Systems setting? I mean, I see this metric makes sense in many document retrieval tasks, but not so much in others (see links below). Any justification of the appropriateness of recall for recommendation will suffice.

Some related literature, which, being honest, I haven't yet read entirely:
http://dl.acm.org/citation.cfm?id=1670600
http://thenoisychannel.com/2009/07/17/in-defense-of-recall
http://thenoisychannel.com/2011/11/14/cikm-2011-industry-event-stephen-robertson-on-why-recall-matters

**Comment by jacekwasilewski** [comment]
I find it useful in following scenario. Imagine we would like to recommend 20 items to a user. We have a dataset where we do not have 20 items for all users, if we split then in the test set we would have even less. Now, we have a user with 2 items in the test set. We have recommended all of these items and 18 other items. Recall would be 1.0, precision would be 0.1. That gives us information that for this user we will not do better in terms of precision. It might be an extreme case, and it is off-line evaluation but it might give better understanding.
Also, I have found few papers it was used as one of evaluation metrics (e.g. http://wanlab.poly.edu/recsys12/recsys/p83.pdf).

**Comment by saulvargas** [comment]
OK, I understand it is a matter of normalisation, as it is done for the nDCG metric. I am good with that.

**Comment by saulvargas** [comment]
Ups... lack of experience in mergin pull requests...

**Pull request merged**
