### PR TITLE
New user intent models

### PR DESCRIPTION
**Pull request by jacekwasilewski**
Hi @saulvargas,

Currently I'm working on different intent models that could be used in the intent-aware framework. I would like to develop new ones in a way that the implementation of xQuAD or ERR-IA doesn't change - I would like to inherit from `IntentModel`.

I needed something that my `NewUserIntentModel` would inherit from and if I just used UserIntentModel I would need to change its constructor implementation as I don't need `prob` variable in that form. If I inherited from `Model<U>`, `get()` and `getModel()` methods wouldn't work in the `IntentModel` class - they wouldn't accept my new class.

I've introduced this `AbstractUserIntentModel` class (I know, name isn't the best but all other that would make sense are already used I think) that extracts common methods - that could be an interface if you have an idea how to name it.

Let me know what you think.

### CODE REVIEW

**Comment by jacekwasilewski** [comment]
I have also added a simple test for UserIntentModel with small mock data. I don't want to break something while developing new things.
You don't have any tests yet, so let me know what you think about that and if you have any suggestions.

**Comment by jacekwasilewski** [comment]
actually I have different idea for testing - as probably in most cases it would be a data-driven testing, Spock framework could be used to make that simpler - I'll check how it would work

**Comment by jacekwasilewski** [comment]
So, I've put a Spock version of the previous test class. I think it looks much better and it works in the same way. What do you think about that?

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

It is definitely a good idea to have more than one intent models. However, I would opt to leave IntentModel (and UserIntentModel) as an interface and then have implementations (the logic of the current one could be moved to a "BasicIntentModel" or "DefaultIntentModel") and, in that way, the code of ERR-IA, xQuAD and other metrics would not need to be modified.

Regarding testing, I guess it is a good practice to include tests for everything, although unit testing is for me one of the most boring activities I have ever had to do. Let me take a look at the test and then I will tell you what I think.

I have not yet taken a look at the actual commit, give me until tomorrow to provide you with my suggestion on how to proceed.

Cheers
Saúl

**Comment by jacekwasilewski** [comment]
I'll modify IntentModel and UserIntentModel as you suggested.

**Comment by saulvargas** [comment]
Done!

**Pull request merged**
